const sortAlphabetically = (arr: string[]) =>
  [...arr].sort((a, b) => a.localeCompare(b))

const sortLanguages = (arr: string[]) => {
  const rest = arr.filter((l) => l !== 'English')
  return ['English', ...sortAlphabetically(rest)]
}

export const COUNTRY_OPTIONS = sortAlphabetically([
  'Turkey',
  'United States',
  'United Kingdom',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Belgium',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Romania',
  'Greece',
  'Portugal',
  'Ukraine',
  'Saudi Arabia',
  'United Arab Emirates',
  'Egypt',
  'India',
  'Pakistan',
  'Indonesia',
  'Malaysia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Singapore',
  'Japan',
  'South Korea',
  'Australia',
  'Canada',
  'Brazil',
])

export const LANGUAGE_OPTIONS = sortLanguages([
  'English',
  'Turkish',
  'Arabic',
  'Spanish',
  'Portuguese',
  'French',
  'German',
  'Italian',
  'Russian',
  'Ukrainian',
  'Polish',
  'Romanian',
  'Greek',
  'Dutch',
  'Swedish',
  'Danish',
  'Norwegian',
  'Finnish',
  'Japanese',
  'Korean',
  'Hindi',
  'Urdu',
  'Indonesian',
  'Malay',
  'Thai',
  'Vietnamese',
  'Tagalog',
])

export const COMMUNICATION_OPTIONS = [
  'Discord',
  'Steam',
  'In-game Voice',
  'In-game Text',
  'Teamspeak',
  'Party Chat',
  'Text Only',
]

export const GAME_OPTIONS = sortAlphabetically([
  'League of Legends',
  'Valorant',
  'Counter-Strike 2',
  'Dota 2',
  'PUBG',
  'Apex Legends',
  'Overwatch 2',
  'Rainbow Six Siege',
  'Rocket League',
  'Fortnite',
  'Call of Duty: Warzone',
  'World of Warcraft',
  'Final Fantasy XIV',
  'Guild Wars 2',
  'Black Desert Online',
  'Lost Ark',
  'Path of Exile',
  'Path of Exile 2',
  'Diablo IV',
  'Warframe',
  'Destiny 2',
  'Dead by Daylight',
  'Sea of Thieves',
  'Phasmophobia',
  'Palworld',
  'Rust',
  'Minecraft',
  'Roblox',
  'GTA Online',
  'Mobile Legends',
])